version: '3.5'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=zhuchechka
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zhuchka
    volumes:
      - pgdata:/var/lib/postgresql/data

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - '8001:8001'
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=zhuchechka
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zhuchka

volumes:
  pgdata: