version: '3.5'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=zhuchechka
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zhuchka
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zhuchechka -d zhuchka"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - '8001:8001'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=zhuchechka
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zhuchka
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  pgdata:
  redisdata: 