version: '3.5'

services:
  db.auth:
    container_name: zhuzhu
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=zhuchechka
    image: postgres:alpine3.18