name: Flutter CI

on:
  push:
    paths:
      - 'frontend/zhuchka_flutter/**'
      - '.github/workflows/flutter.yml'
  pull_request:
    paths:
      - 'frontend/zhuchka_flutter/**'

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/zhuchka_flutter
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: flutter-coverage
          path: frontend/zhuchka_flutter/coverage/lcov.info
